container: docker.io/rpavlyuk/c7-svarog-ci
created: 2017-10-06 16:53:53.501852
name: svarog-ci
ports:
        8080/tcp: 8080
        50000/tcp: 50000
volumes:
        /var/lib/jenkins:
                bind: /var/lib/jenkins
                mode: rw
        /var/www/repo:
                bind: /var/www/repo
                mode: rw
        /sys/fs/cgroup:
                bind: /sys/fs/cgroup
                mode: ro
privileged: true
tty: true
working_dir: /root
command:
        host:
                post: chown -R $(docker exec svarog-ci id -u jenkins | tr -d '\r'):$(docker exec svarog-ci id -g jenkins | tr -d '\r') /var/lib/jenkins
